name: tetrdotjar
main: cabbageroll.tetrdotjar.Pluginmain
version: 1.0
api-version: 1.12.2
commands:
    startgame:
        description: Start/restart game
        usage: /<command>
    sendinput:
        description: Send keyboard inputs
        usage: /<command>
    