name: TETR
main: cabbageroll.tetr.Pluginmain
version: 1.0
api-version: 1.12.2
commands:
    skineditor:
        description: Edit appearance of the blocks
        usage: /<command>
    tetr:
        description: open ui
        usage: /<command>