name: TETR
main: cabbageroll.tetr.Pluginmain
version: 1.0
api-version: 1.12.2
commands:
    skineditor:
        description: Edit appearance of the blocks
        usage: /<command>
    createroom:
        description: Create a room
        usage: /<command>
    room:
        description: Control the room
        usage: /<command>
    joinroom:
        description: Join a room
        usage: /<command>