name: tetrdotjar
main: cabbageroll.tetrdotjar.Pluginmain
version: 1.0
api-version: 1.12.2
commands:
    sendinput:
        description: Send keyboard inputs
        usage: /<command>
    startgame:
        description: singleplayer
        usage: /<command>
    startduel:
        description: 1v1 game
        usage: /<command>
    duelinput:
        description: send duel inputs
        usage: /<command>
    